### ISSUE TITLE
After initial run, internet no longer works unless usbhelperlauncher is open

### ISSUE THREAD

**Issue by acdop100** [FailedShack/USBHelperLauncher#30] opened 2018-12-09 05:27 UTC

**Comment by FailedShack** [comment] 2018-12-09 18:39
Are you sure you're on the latest version of USBHelperLauncher?
This sounds like something that would happen on USBHelperLauncher 0.9 or older.

**Comment by FailedShack** [comment] 2018-12-27 01:34
Closing this since not enough information was provided to reproduce the issue.

**Closed by FailedShack** 2018-12-27 01:34 UTC
Labels: question
