### ISSUE TITLE
locale not configurable?

### ISSUE THREAD

**Issue by Pandoriaantje** [FailedShack/USBHelperLauncher#72] opened 2020-11-09 18:55 UTC
I have a dutch/Belgian win10 system (my kids use this PC too), And I usualle configure my apps to run in English.
I can't find any language setting for Wii U USB Helper, Or the Launcher. Is this intentional? It fetches the system locale, and applies that, withouth user input/choice.

*edit, I currently deleted all locale files except en-US, and that's working.
might want to add a configuration flag somewhere though...

**Comment by FailedShack** [comment] 2020-11-09 21:30
This is a duplicate of #56 

> 
> 
> You can change your preferred language by right-clicking the launcher's tray icon.
> 
> <img alt="Language" width="331" src="https://user-images.githubusercontent.com/39192928/72224792-9169c180-357e-11ea-9309-269052aa5d40.png">

**Closed by FailedShack** 2020-11-09 21:30 UTC
Labels: duplicate
