### ISSUE TITLE
unhandled exception - 404 not found

### ISSUE THREAD

**Issue by fxgopher** [FailedShack/USBHelperLauncher#8] opened 2018-07-25 08:35 UTC
https://hastebin.com/icucidupoy

Last couple of days this has suddenly been happening. Until then it was working fine and had no problems, can you advise on problem and solution - Am Using Firefox 61.01.1 on W10 x64

Thanks

**Comment by FailedShack** [comment] 2018-08-04 17:00
Duplicate of #10

**Closed by FailedShack** 2018-08-04 17:00 UTC
Labels: duplicate
