### ISSUE TITLE
No longer loading and weird error message

### ISSUE THREAD

**Issue by fxgopher** [FailedShack/USBHelperLauncher#15] opened 2018-08-13 20:57 UTC
[
![image2](https://user-images.githubusercontent.com/32275548/44057666-c2e22df6-9f43-11e8-8df0-8615b5a9d699.png)
](url)

**Comment by FailedShack** [comment] 2018-08-13 23:55
Duplicate of #13. Please follow the updated instructions on the Reddit thread.

**Closed by FailedShack** 2018-08-13 23:55 UTC
Labels: duplicate
