### ISSUE TITLE
Data Base not allowing to add more games

### ISSUE THREAD

**Issue by davisrayler** [FailedShack/USBHelperLauncher#38] opened 2018-12-31 06:34 UTC
Despite new games being added to that title keys site... the program wont show them up, this is probably due a data base size limit being reached... please take a look into it! :) 

Thank you.

**Comment by FailedShack** [comment] 2019-01-01 21:31
This is a duplicate of #31. It is not caused by any kind of database limit as it is [JSON-based](https://stackoverflow.com/questions/1262376/is-there-a-limit-on-how-much-json-can-hold).

**Closed by FailedShack** 2019-01-01 21:31 UTC
Labels: duplicate
