### ISSUE TITLE
Downloaded Cemu update but didn't extract

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [FailedShack/USBHelperLauncher#34] opened 2018-12-18 09:13 UTC

**Comment by FailedShack** [comment] 2018-12-18 11:57
USBHelperLauncher will not automatically update Cemu for you. To update your version of Cemu, you have to right click the launcher's tray icon in the taskbar and go to Download Emulator -> Cemu.
Once the new version is downloaded, Wii U USB Helper will pick it up automatically.

**Comment by Pythonic-Rainbow** [comment] 2018-12-18 13:38
But when it was 1.12 , It somehow auto updated from 1.11 🤔 well if so I guess I will have to adapt the new method then

**Comment by Pythonic-Rainbow** [comment] 2019-02-12 14:59
The emulator has auto downloaded Cemu.zip, but is unable to unzip.

**Comment by FailedShack** [comment] 2019-02-22 12:41
I cannot reproduce this, it's unzipped without issue on my end.
Does any error message appear?

**Comment by FailedShack** [comment] 2019-03-23 23:34
Closing. Feel free to reopen this if this is still an issue.

**Closed by FailedShack** 2019-03-23 23:34 UTC
